
PrivateKey: c33e1a0d072aeb744722364d29d9a930bf0173488f6a1d1fc7081a5170695ace

RPCUrl:
    Mainnet:
        Url:https://mainnet.infura.io/v3/92983deb8689407bb1736bdf82bf9c9c
        ChainId:1
    Goerli:
        Url:https://goerli.infura.io/v3/92983deb8689407bb1736bdf82bf9c9c
        ChainId:5
    Lixbtest:
        Url:https://test.lixb.io
        ChainId:2888
APP:
    DefaultPageSize: 10
    MaxPageSize: 100
Log:
    LogSavePath: storage/logs
    LogFileName: app
    LogFileExt: .log

DataBase:
    DBType: mysql
    UserName: root
    Password: 123456
    Host: 127.0.0.1:3306
    DBName:
        TablePrefix: eth_
        Charset: uft8
        ParseTime: True
        MaxIdleConns: 10
        MaxOpenConns: 30